<?php
declare(strict_types=1);

const ROOT = __DIR__ . '/..';
const STORE = ROOT . '/storage';
const UPLOADS = STORE . '/uploads';
require_once ROOT . '/src/Updater.php';
require_once ROOT . '/src/VisionBarcode.php';
if (!is_dir(UPLOADS)) mkdir(UPLOADS, 0750, true);
ini_set('session.use_strict_mode', '1');
session_name('music_collection');
session_set_cookie_params(['lifetime'=>0, 'path'=>'/', 'secure'=>(!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off'), 'httponly'=>true, 'samesite'=>'Lax']);
session_start();
header('X-Frame-Options: DENY');
header('X-Content-Type-Options: nosniff');
header('Referrer-Policy: no-referrer');
header('Permissions-Policy: camera=(self), microphone=()');
header("Content-Security-Policy: default-src 'self'; script-src 'self' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; img-src 'self' https://coverartarchive.org https://*.archive.org blob: data:; media-src 'self' blob:; connect-src 'self' https://cdn.jsdelivr.net; worker-src blob: https://cdn.jsdelivr.net");

function db(): PDO {
    static $db;
    if ($db) return $db;
    $db = new PDO('sqlite:' . STORE . '/music.sqlite', null, null, [PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION, PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);
    $db->exec('PRAGMA foreign_keys = ON');
    $db->exec('CREATE TABLE IF NOT EXISTS users (id INTEGER PRIMARY KEY, email TEXT NOT NULL UNIQUE, password TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP)');
    $db->exec('CREATE TABLE IF NOT EXISTS records (id INTEGER PRIMARY KEY, artist TEXT NOT NULL, title TEXT NOT NULL, format TEXT NOT NULL CHECK(format IN ("CD","LP")), barcode TEXT, tracklist TEXT, release_year INTEGER, duration_seconds INTEGER, cover_path TEXT, back_path TEXT, barcode_path TEXT, created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP, deleted_at TEXT, user_id INTEGER NOT NULL REFERENCES users(id))');
    try { $db->exec('ALTER TABLE records ADD COLUMN deleted_at TEXT'); } catch (Throwable $e) {}
    try { $db->exec('ALTER TABLE records ADD COLUMN release_year INTEGER'); } catch (Throwable $e) {}
    try { $db->exec('ALTER TABLE records ADD COLUMN duration_seconds INTEGER'); } catch (Throwable $e) {}
    try { $db->exec('ALTER TABLE records ADD COLUMN is_compilation INTEGER NOT NULL DEFAULT 0'); } catch (Throwable $e) {}
    try { $db->exec('ALTER TABLE records ADD COLUMN track_artists TEXT'); } catch (Throwable $e) {}
    try { $db->exec('ALTER TABLE records ADD COLUMN musicbrainz_release_group TEXT'); } catch (Throwable $e) {}
    try { $db->exec('ALTER TABLE records ADD COLUMN cover_thumb_path TEXT'); } catch (Throwable $e) {}
    $db->exec('CREATE INDEX IF NOT EXISTS records_barcode ON records(barcode)');
    return $db;
}
function e(?string $value): string { return htmlspecialchars($value ?? '', ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
function playtime(?int $seconds): string { if (!$seconds) return 'Onbekend'; return floor($seconds / 60) . ':' . str_pad((string)($seconds % 60), 2, '0', STR_PAD_LEFT); }
function listLines(string $value): array { return array_values(array_filter(array_map('trim',preg_split('/\R/',trim($value)) ?: []),fn($line)=>$line!=='')); }
function normalizedTrackArtists(string $tracks, string $trackArtists, string $albumArtist, bool $compilation): string { $titles=listLines($tracks);$artists=listLines($trackArtists);if(!$titles)return '';if(!$artists&&!$compilation)return implode("\n",array_fill(0,count($titles),$albumArtist));if(count($artists)!==count($titles))throw new RuntimeException('Voer voor elk nummer precies één uitvoerende artiest in, in dezelfde volgorde.');return implode("\n",$artists); }
function artistCredit(array $credit): string { $name='';foreach($credit as $part)$name.=($part['name']??'').($part['joinphrase']??'');return trim($name); }
function tracklistDisplay(array $record): string { $titles=listLines((string)($record['tracklist']??''));$artists=listLines((string)($record['track_artists']??''));if(!$titles)return '<p class="tracklist">Niet vastgelegd.</p>';$rows='';foreach($titles as $index=>$title)$rows.='<li><span>'.e($title).'</span>'.(!empty($record['is_compilation'])?'<strong>'.e($artists[$index]??'Onbekend').'</strong>':'').'</li>';return '<ol class="tracklist tracklist-compilation '.(empty($record['is_compilation'])?'tracklist-single':'').'">'.$rows.'</ol>'; }
function loggedIn(): bool { return isset($_SESSION['user_id']); }
function requireLogin(): void { if (!loggedIn()) { header('Location: ?page=login'); exit; } }
function csrf(): string { if (empty($_SESSION['csrf'])) $_SESSION['csrf']=bin2hex(random_bytes(32)); return $_SESSION['csrf']; }
function checkCsrf(): void { if (!hash_equals($_SESSION['csrf'] ?? '', $_POST['csrf'] ?? '')) { http_response_code(403); exit('Ongeldig formulierverzoek. Vernieuw de pagina en probeer opnieuw.'); } }
function flash(string $message, string $type='ok'): void { $_SESSION['flash']=[$message,$type]; }
function redirect(string $url): void { header('Location: '.$url); exit; }
function imageUpload(string $key): ?string {
    if (empty($_FILES[$key]['tmp_name']) || $_FILES[$key]['error'] === UPLOAD_ERR_NO_FILE) return null;
    if ($_FILES[$key]['error'] !== UPLOAD_ERR_OK || $_FILES[$key]['size'] > 10 * 1024 * 1024) throw new RuntimeException('Elke foto moet kleiner zijn dan 10 MB.');
    $mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES[$key]['tmp_name']);
    $extensions=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
    if (!isset($extensions[$mime])) throw new RuntimeException('Gebruik een JPG, PNG of WebP-afbeelding.');
    $name=bin2hex(random_bytes(20)).'.'.$extensions[$mime];
    if (!move_uploaded_file($_FILES[$key]['tmp_name'], UPLOADS.'/'.$name)) throw new RuntimeException('Foto kon niet veilig opgeslagen worden.');
    return $name;
}
function thumbnailForCover(?string $cover): ?string {
    if (!$cover || !is_file(UPLOADS.'/'.$cover) || !function_exists('imagecreatefromstring') || !function_exists('imagejpeg')) return null;
    $source=@imagecreatefromstring((string)file_get_contents(UPLOADS.'/'.$cover));if(!$source)return null;
    $width=imagesx($source);$height=imagesy($source);if(!$width||!$height){imagedestroy($source);return null;}
    $scale=min(100/$width,100/$height,1);$targetWidth=max(1,(int)round($width*$scale));$targetHeight=max(1,(int)round($height*$scale));
    $target=imagecreatetruecolor($targetWidth,$targetHeight);imagefill($target,0,0,imagecolorallocate($target,255,255,255));imagecopyresampled($target,$source,0,0,0,0,$targetWidth,$targetHeight,$width,$height);
    $directory=UPLOADS.'/covers/thumbs';if(!is_dir($directory)&&!mkdir($directory,0750,true)&&!is_dir($directory)){imagedestroy($source);imagedestroy($target);return null;}
    $name='covers/thumbs/'.bin2hex(random_bytes(20)).'.jpg';$saved=imagejpeg($target,UPLOADS.'/'.$name,82);imagedestroy($source);imagedestroy($target);return $saved?$name:null;
}
function outputCoverForBarcode(string $barcode): never {
    $safe=preg_replace('/[^0-9A-Za-z]/','',$barcode);
    $context=stream_context_create(['http'=>['header'=>"User-Agent: MijnMuziekCollectie/1.0 (personal collection app)\r\nAccept: application/json\r\n",'timeout'=>8,'follow_location'=>1]]);
    $raw=@file_get_contents('https://musicbrainz.org/ws/2/release?query=barcode:'.rawurlencode($safe).'&fmt=json&limit=1',false,$context);
    $data=$raw?json_decode($raw,true):null; $id=$data['releases'][0]['id']??'';
    if (!preg_match('/^[a-f0-9-]{36}$/i',$id)) { http_response_code(404); exit; }
    $url='https://coverartarchive.org/release/'.rawurlencode($id).'/front-250';
    $image=@file_get_contents($url,false,$context);
    if ($image===false) { http_response_code(404); exit; }
    foreach ($http_response_header ?? [] as $header) if (stripos($header,'Content-Type:')===0) { header($header); break; }
    header('Cache-Control: private, max-age=604800'); echo $image; exit;
}
function musicRelease(string $barcode): array {
    $safe=preg_replace('/[^0-9A-Za-z]/','',$barcode);
    $context=stream_context_create(['http'=>['header'=>"User-Agent: MijnMuziekCollectie/1.0 (personal collection app)\r\nAccept: application/json\r\n",'timeout'=>10]]);
    $raw=@file_get_contents('https://musicbrainz.org/ws/2/release?query=barcode:'.rawurlencode($safe).'&fmt=json&limit=1',false,$context);
    $search=$raw?json_decode($raw,true):null; $release=$search['releases'][0]??null; if (!$release) throw new RuntimeException('Geen albumgegevens gevonden voor deze barcode.');
    $detail=@file_get_contents('https://musicbrainz.org/ws/2/release/'.rawurlencode($release['id']).'?inc=recordings+artist-credits&fmt=json',false,$context);
    $full=$detail?json_decode($detail,true):$release; $artist=artistCredit($full['artist-credit']??[]); $title=$full['title']??'';
    if (!$artist || !$title) throw new RuntimeException('De gevonden uitgave bevat geen bruikbare artiest of titel.');
    $tracks=[];$trackArtists=[];$duration=0; foreach($full['media']??[] as $medium) foreach($medium['tracks']??[] as $track) {$tracks[]=($track['number']??'').'. '.($track['title']??'');$trackArtists[]=artistCredit($track['artist-credit']??$track['recording']['artist-credit']??[])?:$artist;$duration+=(int)(($track['length']??$track['recording']['length']??0)/1000);}
    $mediumFormat=(string)($full['media'][0]['format']??''); $format=str_contains(strtolower($mediumFormat),'vinyl')?'LP':'CD';
    $releaseDate=(string)($full['date']??$release['date']??$full['release-events'][0]['date']??$release['release-events'][0]['date']??'');$year=preg_match('/^(\d{4})/',$releaseDate,$match)?(int)$match[1]:null;
    $releaseGroupId=$full['release-group']['id']??$release['release-group']['id']??null;
    $groupData=$releaseGroupId?json_decode((string)@file_get_contents('https://musicbrainz.org/ws/2/release-group/'.rawurlencode($releaseGroupId).'?fmt=json',false,$context),true):null;
    $secondary=$groupData['secondary-types']??$full['release-group']['secondary-types']??$release['release-group']['secondary-types']??[];
    $isCompilation=in_array('Compilation',$secondary,true) || in_array('compilation',$secondary,true) || strtolower($artist)==='various artists';
    if($isCompilation)$artist='Various Artists';
    return ['id'=>$full['id']??$release['id'],'release_group'=>$releaseGroupId,'artist'=>$artist,'title'=>$title,'format'=>$format,'year'=>$year,'duration_seconds'=>$duration?:null,'tracklist'=>implode("\n",$tracks),'track_artists'=>implode("\n",$trackArtists),'is_compilation'=>$isCompilation];
}
function downloadCover(string $releaseId, ?string $releaseGroupId=null, ?string &$error=null): ?string {
    $error=null;
    if (!preg_match('/^[a-f0-9-]{36}$/i',$releaseId)) return null;
    $urls=['https://coverartarchive.org/release/'.rawurlencode($releaseId).'/front-500'];
    if ($releaseGroupId && preg_match('/^[a-f0-9-]{36}$/i',$releaseGroupId)) $urls[]='https://coverartarchive.org/release-group/'.rawurlencode($releaseGroupId).'/front-500';
    $image=null;$type='';foreach($urls as $url){$curl=curl_init($url);curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_TIMEOUT=>20,CURLOPT_USERAGENT=>'MijnMuziekCollectie/1.0']);$candidate=curl_exec($curl);$status=(int)curl_getinfo($curl,CURLINFO_HTTP_CODE);$candidateType=(string)curl_getinfo($curl,CURLINFO_CONTENT_TYPE);curl_close($curl);if(is_string($candidate)&&$status===200&&strlen($candidate)>1000){$image=$candidate;$type=$candidateType;break;}}
    if (!is_string($image)) return null;
    $mime=explode(';',$type)[0];$ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null;if(!$ext)return null;
    $dir=UPLOADS.'/covers';if(!is_dir($dir) && !mkdir($dir,0750,true) && !is_dir($dir)){$error='De hoes kon niet lokaal worden opgeslagen: de opslagmap is niet schrijfbaar.';return null;}$name='covers/'.bin2hex(random_bytes(20)).'.'.$ext;
    if(file_put_contents(UPLOADS.'/'.$name,$image,LOCK_EX)===false){$error='De hoes kon niet lokaal worden opgeslagen. Controleer schrijfrechten op storage/uploads/covers.';return null;}return $name;
}
function layout(string $title, string $content): never {
    $flash=$_SESSION['flash'] ?? null; unset($_SESSION['flash']); $logged=loggedIn(); $page=$_GET['page'] ?? 'dashboard';
    $assetVersion=rawurlencode((json_decode((string)@file_get_contents(ROOT.'/version.json'),true)['version']??'dev'));
    $nav=$logged ? '<button id="menu-toggle" class="menu-toggle" type="button" aria-label="Menu openen" aria-controls="site-nav" aria-expanded="false">☰</button><nav id="site-nav"><a class="'.($page==='dashboard'?'active':'').'" href="?page=dashboard">Collectie</a><a class="'.($page==='add'?'active':'').'" href="?page=add">Handmatig toevoegen</a><a class="mobile-scan-link '.($page==='scan'?'active':'').'" href="?page=scan">Scannen</a><a class="'.($page==='trash'?'active':'').'" href="?page=trash">Prullenbak</a><a class="'.($page==='integrations'?'active':'').'" href="?page=integrations">Integraties</a><a href="?action=logout">Uitloggen</a></nav>' : '';
    $nav=str_replace('</nav>','<a id="update-button" class="update-link" href="?page=updates">Updates</a></nav>',$nav);
    $content='<i id="csrf-token" data-token="'.csrf().'" hidden></i>'.$content;
    $content.='<link rel="stylesheet" href="assets/collection-list.css?v='.$assetVersion.'"><link rel="stylesheet" href="assets/collection-filters.css?v='.$assetVersion.'"><link rel="stylesheet" href="assets/filter-visibility.css?v='.$assetVersion.'"><link rel="stylesheet" href="assets/music-metadata.css?v='.$assetVersion.'"><link rel="stylesheet" href="assets/track-fields.css?v='.$assetVersion.'"><link rel="stylesheet" href="assets/navigation.css?v='.$assetVersion.'"><link rel="stylesheet" href="assets/mobile-menu.css?v='.$assetVersion.'"><link rel="stylesheet" href="assets/scan.css?v='.$assetVersion.'"><link rel="stylesheet" href="assets/update.css?v='.$assetVersion.'"><script src="assets/update.js?v='.$assetVersion.'" defer></script><script src="assets/direct-scanner.js?v='.$assetVersion.'" defer></script>';
    $notice=$flash ? '<div class="notice '.($flash[1]==='error'?'error':'').'">'.e($flash[0]).'</div>' : '';
    echo '<!doctype html><html lang="nl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><meta name="theme-color" content="#e8466d"><title>'.e($title).' · Mijn Muziek</title><link rel="stylesheet" href="assets/app.css?v='.$assetVersion.'"></head><body><main class="shell"><header class="topbar"><a class="brand" href="?page=dashboard">mijn<span>muziek</span></a>'.$nav.'</header>'.$notice.$content.'</main><script src="assets/app.js?v='.$assetVersion.'" defer></script></body></html>'; exit;
}

if (($_GET['action'] ?? '') === 'logout') { session_unset(); session_destroy(); redirect('?page=login'); }
if (($_GET['action'] ?? '') === 'image') { requireLogin(); $id=(int)($_GET['id']??0);$kind=$_GET['kind']??'cover';$field=$kind==='back'?'back_path':($kind==='barcode'?'barcode_path':'cover_path');$thumbnail=$field==='cover_path'&&($_GET['size']??'')==='thumb';$s=db()->prepare('SELECT cover_path,cover_thumb_path,back_path,barcode_path,barcode FROM records WHERE id=? AND user_id=?');$s->execute([$id,$_SESSION['user_id']]);$row=$s->fetch()?:[];$name=$thumbnail?($row['cover_thumb_path']??null):($row[$field]??null);if($thumbnail&&(!$name||!is_file(UPLOADS.'/'.$name))&&!empty($row['cover_path'])){$name=thumbnailForCover($row['cover_path']);if($name)db()->prepare('UPDATE records SET cover_thumb_path=? WHERE id=? AND user_id=?')->execute([$name,$id,$_SESSION['user_id']]);}$path=$name?UPLOADS.'/'.$name:'';$fallback=null;if((!$name||!is_file($path))&&$field==='cover_path'&&!empty($row['barcode'])){try{$release=musicRelease($row['barcode']);$cover=downloadCover($release['id'],$release['release_group']);if($cover){$thumb=thumbnailForCover($cover);db()->prepare('UPDATE records SET cover_path=?,cover_thumb_path=? WHERE id=? AND user_id=?')->execute([$cover,$thumb,$id,$_SESSION['user_id']]);$name=$thumbnail?($thumb?:$cover):$cover;$path=UPLOADS.'/'.$name;}else $fallback='https://coverartarchive.org/release/'.rawurlencode($release['id']).'/front-500';}catch(Throwable $e){}}if((!$name||!is_file($path))&&$thumbnail&&!empty($row['cover_path'])&&is_file(UPLOADS.'/'.$row['cover_path'])){$name=$row['cover_path'];$path=UPLOADS.'/'.$name;}if((!$name||!is_file($path))&&$fallback){header('Location: '.$fallback,true,302);exit;}if(!$name||!is_file($path)){http_response_code(404);exit;}$mime=(new finfo(FILEINFO_MIME_TYPE))->file($path);header('Content-Type: '.$mime);header('X-Content-Type-Options: nosniff');header('Cache-Control: private, max-age=86400');readfile($path);exit; }
if (($_GET['action'] ?? '') === 'update-status') { requireLogin(); header('Content-Type: application/json'); $local=json_decode((string)@file_get_contents(ROOT.'/version.json'),true); $current=$local['version']??'0.0.0'; if (!function_exists('curl_init')) { http_response_code(503); echo json_encode(['error'=>'cURL is niet beschikbaar op deze hosting.']); exit; } $curl=curl_init('https://raw.githubusercontent.com/gitreprtc/mymusiccollection/main/version.json'); curl_setopt_array($curl,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_FOLLOWLOCATION=>true,CURLOPT_TIMEOUT=>10,CURLOPT_CONNECTTIMEOUT=>5,CURLOPT_USERAGENT=>'MijnMuziekCollectie updater/1.0',CURLOPT_HTTPHEADER=>['Accept: application/json']]); $raw=curl_exec($curl); $status=(int)curl_getinfo($curl,CURLINFO_HTTP_CODE); curl_close($curl); $remote=is_string($raw)?json_decode($raw,true):null; if ($status!==200 || !is_array($remote) || empty($remote['version'])) { http_response_code(503); echo json_encode(['error'=>'GitHub-versie is niet bereikbaar.']); exit; } echo json_encode(['current'=>$current,'version'=>$remote['version'],'available'=>version_compare($remote['version'],$current,'>'),'url'=>'https://github.com/gitreprtc/mymusiccollection']); exit; }
if (($_GET['action'] ?? '') === 'runtime') { requireLogin(); header('Content-Type: application/json'); $version=json_decode((string)@file_get_contents(ROOT.'/version.json'),true)['version']??'onbekend'; echo json_encode(['version'=>$version,'vision_configured'=>VisionBarcode::configured(),'scanner'=>'vision-photo']); exit; }
if (($_GET['action'] ?? '') === 'vision-barcode') { requireLogin(); header('Content-Type: application/json'); checkCsrf(); try { if (empty($_FILES['barcode_photo']['tmp_name']) || $_FILES['barcode_photo']['error'] !== UPLOAD_ERR_OK || $_FILES['barcode_photo']['size'] > 10 * 1024 * 1024) throw new RuntimeException('Maak eerst een barcodefoto van maximaal 10 MB.'); $mime=(new finfo(FILEINFO_MIME_TYPE))->file($_FILES['barcode_photo']['tmp_name']); $ext=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'][$mime]??null; if (!$ext) throw new RuntimeException('Gebruik een JPG, PNG of WebP-foto.'); $dir=UPLOADS.'/scans'; if (!is_dir($dir)) mkdir($dir,0750,true); $name='scans/'.bin2hex(random_bytes(20)).'.'.$ext; if (!move_uploaded_file($_FILES['barcode_photo']['tmp_name'],UPLOADS.'/'.$name)) throw new RuntimeException('Barcodefoto kon niet veilig worden opgeslagen.'); echo json_encode(['barcode' => VisionBarcode::read(UPLOADS.'/'.$name), 'scan_photo' => $name]); } catch (Throwable $e) { http_response_code(422); echo json_encode(['error' => $e->getMessage()]); } exit; }
if (($_GET['action'] ?? '') === 'lookup') { requireLogin(); header('Content-Type: application/json'); $barcode=preg_replace('/[^0-9A-Za-z]/','',$_GET['barcode']??''); if (strlen($barcode)<6) { http_response_code(422); echo json_encode(['error'=>'Ongeldige barcode.']); exit; } try { $release=musicRelease($barcode); echo json_encode(['release'=>['title'=>$release['title'],'artist'=>$release['artist'],'collectionFormat'=>$release['format'],'tracks'=>$release['tracklist'],'track_artists'=>$release['track_artists'],'year'=>$release['year'],'duration_seconds'=>$release['duration_seconds'],'is_compilation'=>$release['is_compilation']]]); } catch(Throwable $e) { http_response_code(404); echo json_encode(['error'=>$e->getMessage()]); } exit; }
if (($_GET['action'] ?? '') === 'check') { requireLogin(); header('Content-Type: application/json'); $barcode=preg_replace('/\D/','',$_GET['barcode']??'');$alternate=strlen($barcode)===12?'0'.$barcode:(strlen($barcode)===13&&str_starts_with($barcode,'0')?substr($barcode,1):$barcode); $s=db()->prepare('SELECT artist,title,format FROM records WHERE barcode IN (?,?) AND user_id=? AND deleted_at IS NULL LIMIT 1'); $s->execute([$barcode,$alternate,$_SESSION['user_id']]); $r=$s->fetch();if($r){echo json_encode(['found'=>true]+$r);exit;}try{$release=musicRelease($barcode);$same=db()->prepare('SELECT artist,title,format FROM records WHERE user_id=? AND deleted_at IS NULL AND ((musicbrainz_release_group IS NOT NULL AND musicbrainz_release_group=?) OR (lower(artist)=lower(?) AND lower(title)=lower(?))) ORDER BY id DESC');$same->execute([$_SESSION['user_id'],$release['release_group'],$release['artist'],$release['title']]);echo json_encode(['found'=>false,'release'=>$release,'same_album'=>$same->fetchAll()]);}catch(Throwable $e){echo json_encode(['found'=>false,'release'=>null,'same_album'=>[]]);}exit; }
if (($_GET['action'] ?? '') === 'add-from-barcode') { requireLogin(); header('Content-Type: application/json'); checkCsrf(); try { $barcode=preg_replace('/[^0-9A-Za-z]/','',$_POST['barcode']??''); if (strlen($barcode)<8) throw new RuntimeException('Ongeldige barcode.'); $existing=db()->prepare('SELECT id FROM records WHERE barcode=? AND user_id=? AND deleted_at IS NULL'); $existing->execute([$barcode,$_SESSION['user_id']]); if ($existing->fetch()) throw new RuntimeException('Deze uitgave staat al in je collectie.'); $release=musicRelease($barcode); $photo=$_POST['scan_photo']??''; if (!preg_match('#^scans/[a-f0-9]{40}\.(jpg|png|webp)$#',$photo) || !is_file(UPLOADS.'/'.$photo)) $photo=null; $coverError=null;$cover=downloadCover($release['id'],$release['release_group'],$coverError);$thumb=thumbnailForCover($cover); db()->prepare('INSERT INTO records(artist,title,format,barcode,tracklist,track_artists,release_year,duration_seconds,cover_path,cover_thumb_path,barcode_path,is_compilation,musicbrainz_release_group,user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$release['artist'],$release['title'],$release['format'],$barcode,$release['tracklist'],$release['track_artists'],$release['year'],$release['duration_seconds'],$cover,$thumb,$photo,$release['is_compilation']?1:0,$release['release_group'],$_SESSION['user_id']]); echo json_encode($release+['cover_warning'=>$coverError]); } catch(Throwable $e) { http_response_code(422); echo json_encode(['error'=>$e->getMessage()]); } exit; }

$count=(int)db()->query('SELECT COUNT(*) FROM users')->fetchColumn();
if ($_SERVER['REQUEST_METHOD']==='POST') {
    checkCsrf(); $form=$_POST['form']??'';
    try {
        if ($form==='setup' && $count===0) { $email=filter_var(trim($_POST['email']??''),FILTER_VALIDATE_EMAIL); $pass=$_POST['password']??''; if(!$email||strlen($pass)<12) throw new RuntimeException('Gebruik een geldig e-mailadres en een wachtzin van minimaal 12 tekens.'); $algo=defined('PASSWORD_ARGON2ID')?PASSWORD_ARGON2ID:PASSWORD_BCRYPT; db()->prepare('INSERT INTO users(email,password) VALUES (?,?)')->execute([$email,password_hash($pass,$algo)]); session_regenerate_id(true); $_SESSION['user_id']=db()->lastInsertId(); flash('Account veilig aangemaakt.'); redirect('?page=dashboard'); }
        if ($form==='login') { $s=db()->prepare('SELECT * FROM users WHERE email=?');$s->execute([trim($_POST['email']??'')]);$u=$s->fetch(); if(!$u||!password_verify($_POST['password']??'',$u['password'])) throw new RuntimeException('E-mailadres of wachtwoord klopt niet.'); session_regenerate_id(true);$_SESSION['user_id']=$u['id'];flash('Welkom terug.');redirect('?page=dashboard'); }
        requireLogin();
        if ($form==='delete_record') { $id=(int)($_POST['id']??0); db()->prepare('UPDATE records SET deleted_at=CURRENT_TIMESTAMP WHERE id=? AND user_id=? AND deleted_at IS NULL')->execute([$id,$_SESSION['user_id']]); flash('Uitgave verplaatst naar de prullenbak.'); redirect('?page=trash'); }
        if ($form==='update_compilation') { $id=(int)($_POST['id']??0); db()->prepare('UPDATE records SET is_compilation=? WHERE id=? AND user_id=? AND deleted_at IS NULL')->execute([isset($_POST['is_compilation'])?1:0,$id,$_SESSION['user_id']]); flash('Verzamelalbum-label bijgewerkt.'); redirect('?page=record&id='.$id); }
        if ($form==='refresh_record') { $id=(int)($_POST['id']??0);$s=db()->prepare('SELECT barcode FROM records WHERE id=? AND user_id=? AND deleted_at IS NULL');$s->execute([$id,$_SESSION['user_id']]);$record=$s->fetch();if(!$record||empty($record['barcode']))throw new RuntimeException('Dit album heeft geen barcode om MusicBrainz te raadplegen.');$release=musicRelease($record['barcode']);db()->prepare('UPDATE records SET artist=?,title=?,format=?,tracklist=?,track_artists=?,release_year=?,duration_seconds=?,is_compilation=?,musicbrainz_release_group=? WHERE id=? AND user_id=? AND deleted_at IS NULL')->execute([$release['artist'],$release['title'],$release['format'],$release['tracklist'],$release['track_artists'],$release['year'],$release['duration_seconds'],$release['is_compilation']?1:0,$release['release_group'],$id,$_SESSION['user_id']]);flash('Albumgegevens opnieuw opgehaald uit MusicBrainz.');redirect('?page=record&id='.$id); }
        if ($form==='empty_trash') { $items=db()->prepare('SELECT cover_path,cover_thumb_path,back_path,barcode_path FROM records WHERE user_id=? AND deleted_at IS NOT NULL');$items->execute([$_SESSION['user_id']]);foreach($items as $item)foreach(['cover_path','cover_thumb_path','back_path','barcode_path'] as $field)if(!empty($item[$field])&&is_file(UPLOADS.'/'.$item[$field]))unlink(UPLOADS.'/'.$item[$field]);db()->prepare('DELETE FROM records WHERE user_id=? AND deleted_at IS NOT NULL')->execute([$_SESSION['user_id']]);flash('Prullenbak geleegd.');redirect('?page=trash'); }
        if ($form==='openai_settings') { if (($_POST['mode']??'')==='remove') VisionBarcode::removeKey(); else VisionBarcode::saveKey($_POST['openai_api_key']??''); flash('OpenAI-integratie bijgewerkt.'); redirect('?page=integrations'); }
        if ($form==='apply_update') { if (empty($_SERVER['HTTPS']) || $_SERVER['HTTPS']==='off') throw new RuntimeException('Updates zijn uitsluitend via HTTPS toegestaan.'); $message=Updater::install(ROOT, STORE); flash($message); redirect('?page=updates'); }
        if ($form==='record') { $artist=trim($_POST['artist']??'');$title=trim($_POST['title']??'');$format=$_POST['format']??'';$compilation=isset($_POST['is_compilation']);if($compilation)$artist='Various Artists';if(!$artist||!$title||!in_array($format,['CD','LP'],true)) throw new RuntimeException('Artiest, titel en type zijn verplicht.');$tracks=trim($_POST['tracklist']??'');$trackArtists=normalizedTrackArtists($tracks,trim($_POST['track_artists']??''),$artist,$compilation);$cover=imageUpload('cover');$thumb=thumbnailForCover($cover); db()->prepare('INSERT INTO records(artist,title,format,barcode,tracklist,track_artists,release_year,duration_seconds,cover_path,cover_thumb_path,is_compilation,user_id) VALUES(?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$artist,$title,$format,trim($_POST['barcode']??''),$tracks,$trackArtists,(int)($_POST['release_year']??0)?:null,(int)($_POST['duration_seconds']??0)?:null,$cover,$thumb,$compilation?1:0,$_SESSION['user_id']]);flash('Toegevoegd aan je collectie.');redirect('?page=dashboard'); }
    } catch(Throwable $e) { flash($e->getMessage(),'error'); redirect('?page='.($form==='record'?'add':($form==='refresh_record'?'record&id='.(int)($_POST['id']??0):($form==='setup'?'setup':($form==='openai_settings'?'integrations':'login'))))); }
}

if ($count===0) layout('Eerste installatie','<section class="card auth"><h1>Maak je kluis</h1><p>Dit is een eenmalige stap. Kies een sterk wachtwoord; er is geen standaardaccount.</p><form method="post"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="form" value="setup"><label>E-mailadres</label><input type="email" name="email" autocomplete="email" required><label>Wachtzin <span class="muted">(minimaal 12 tekens)</span></label><input type="password" name="password" minlength="12" autocomplete="new-password" required><div class="actions"><button>Account aanmaken</button></div></form></section>');
$page=$_GET['page']??(loggedIn()?'dashboard':'login'); if(!loggedIn()&&$page!=='login') redirect('?page=login');
if($page==='login') layout('Inloggen','<section class="card auth"><h1>Welkom terug</h1><p>Log in om je muziekcollectie te bekijken.</p><form method="post"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="form" value="login"><label>E-mailadres</label><input type="email" name="email" autocomplete="email" required><label>Wachtwoord</label><input type="password" name="password" autocomplete="current-password" required><div class="actions"><button>Inloggen</button></div></form></section>');
requireLogin();
if($page==='add') layout('Handmatig toevoegen','<section class="hero"><h1>Handmatig toevoegen.</h1><p>Vul de gegevens zelf in. Voor automatisch scannen gebruik je het scherm Scannen.</p></section><section class="card"><form method="post" enctype="multipart/form-data"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="form" value="record"><div class="form-grid"><div><label>Artiest</label><input id="artist" name="artist" required></div><div><label>Titel</label><input id="title" name="title" required></div><div><label>Type</label><select id="format" name="format" required><option value="CD">CD</option><option value="LP">LP / vinyl</option></select></div><div><label>Barcode</label><input id="barcode" name="barcode" inputmode="numeric" placeholder="Bijv. 871..." aria-describedby="lookup-status"><p id="lookup-status" class="muted">Na het verlaten van dit veld zoeken we automatisch in MusicBrainz.</p></div><div><label>Jaar</label><input id="release_year" name="release_year" inputmode="numeric" min="1000" max="9999"></div><div><label>Lengte <span class="muted">(seconden)</span></label><input id="duration_seconds" name="duration_seconds" inputmode="numeric" min="0"></div><div class="span-2 checkbox-field"><label><input id="is_compilation" type="checkbox" name="is_compilation" value="1"> Verzamelalbum</label><p class="muted">Bij een verzamelalbum wordt de albumartiest automatisch Various Artists.</p></div><div class="span-2"><label>Albumhoes uploaden</label><input type="file" name="cover" accept="image/*" capture="environment"><p class="muted">Kies een bestaande scan of maak direct een foto van de albumhoes.</p></div><div class="span-2 track-inputs"><div><label>Tracknamen</label><textarea id="tracklist" name="tracklist" placeholder="Eén nummer per regel"></textarea></div><div><label>Uitvoerende artiesten</label><textarea id="track_artists" name="track_artists" placeholder="Eén artiest per regel, in dezelfde volgorde"></textarea></div></div><p class="span-2 muted">De twee lijsten horen regel voor regel bij elkaar. Bij een regulier album vult de app de albumartiest als uitvoerende artiest in als deze lijst leeg blijft.</p></div><div class="actions"><button>Opslaan in collectie</button></div></form></section>');
if($page==='integrations') { $state=VisionBarcode::configured()?'Actief':'Niet ingesteld'; layout('Integraties','<section class="card auth"><h1>OpenAI Vision</h1><p>Gebruik vision-herkenning om de cijfers onder een barcode betrouwbaar uit te lezen.</p><p><span class="tag">'.e($state).'</span></p><p class="muted">Standaardmodel: GPT-5 nano — geoptimaliseerd voor een snelle, zuinige barcode-opvraag.</p><form method="post"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="form" value="openai_settings"><input type="hidden" name="mode" value="save"><label>OpenAI API-sleutel</label><input type="password" name="openai_api_key" autocomplete="new-password" placeholder="sk-..." required><p class="muted">De sleutel wordt buiten de webmap opgeslagen, nooit weergegeven en nooit naar GitHub gestuurd.</p><div class="actions"><button>Integratie opslaan</button></div></form>'.(VisionBarcode::configured()?'<form method="post"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="form" value="openai_settings"><input type="hidden" name="mode" value="remove"><div class="actions"><button class="secondary" type="submit">Sleutel verwijderen</button></div></form>':'').'</section>'); }
if($page==='updates') layout('Updates','<section class="card auth"><h1>Software-update</h1><p id="update-message" class="muted">Controleren of er een nieuwe versie is…</p><p>Updates worden via HTTPS van de openbare GitHub-repository opgehaald. Je database en foto’s blijven staan; vóór installatie maakt de app een back-up in <code>storage/backups</code>.</p><div class="actions"><button id="check-updates" class="secondary" type="button">Nu controleren op updates</button></div><form id="install-update-form" method="post" hidden><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="form" value="apply_update"><div class="actions"><button id="install-update" type="submit">Update installeren</button></div></form></section>');
if($page==='scan') { $storeMode=($_GET['mode']??'')==='store';$title=$storeMode?'Scan in winkel':'Barcode lezen';$heading=$storeMode?'Heb ik deze al?':'Album toevoegen via scan';$intro=$storeMode?'Controleer in de winkel of je deze CD of LP al bezit. Er wordt nooit iets toegevoegd.':'Maak een foto met de achtercamera; nieuwe uitgaven kun je na controle toevoegen.';$switch=$storeMode?'<a class="button secondary" href="?page=scan">Naar toevoegen via scan</a>':'<a class="button secondary" href="?page=scan&amp;mode=store">Scan in winkel</a>';layout($title,'<section class="card scan-box"><h1>'.$heading.'</h1><p class="muted">'.$intro.'</p><video id="scanner-video" hidden playsinline style="width:100%;border-radius:12px"></video><div class="actions" style="justify-content:center"><button id="start-scan">Open achtercamera</button>'.$switch.'</div><p id="scan-status" class="muted"></p><div id="scan-result" class="scan-result">Nog niets gecontroleerd.</div></section>'); }
if($page==='trash') { $s=db()->prepare('SELECT * FROM records WHERE user_id=? AND deleted_at IS NOT NULL ORDER BY deleted_at DESC');$s->execute([$_SESSION['user_id']]);$trash=$s->fetchAll();$items='';foreach($trash as $r)$items.='<article class="record"><div class="record-body"><span class="tag">'.e($r['format']).'</span><h2>'.e($r['artist']).'</h2><p>'.e($r['title']).'</p></div></article>';layout('Prullenbak','<section class="hero"><h1>Prullenbak</h1><p>Verwijderde uitgaven staan hier tot je de prullenbak leegt.</p></section>'.($items?'<section class="collection collection-list">'.$items.'</section><form method="post"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="form" value="empty_trash"><div class="actions"><button>Prullenbak definitief legen</button></div></form>':'<section class="card empty">De prullenbak is leeg.</section>')); }
if($page==='record') { $s=db()->prepare('SELECT * FROM records WHERE id=? AND user_id=? AND deleted_at IS NULL');$s->execute([(int)($_GET['id']??0),$_SESSION['user_id']]);$r=$s->fetch();if(!$r){http_response_code(404);layout('Niet gevonden','<p>Deze uitgave bestaat niet.</p>');}$cover=($r['cover_path']||$r['barcode'])?'<img src="?action=image&id='.$r['id'].'" alt="Voorkant van '.e($r['title']).'">':'<div class="cover"></div>';$year=$r['release_year']?(string)$r['release_year']:'Onbekend';$added=date('d-m-Y',strtotime($r['created_at']));$tags='<span class="tag '.($r['format']==='LP'?'tag-lp':'').'">'.e($r['format']).'</span>'.($r['is_compilation']?'<span class="tag tag-compilation">Verzamelalbum</span>':'');$compilationControl='<form method="post" class="compilation-control"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="form" value="update_compilation"><input type="hidden" name="id" value="'.$r['id'].'"><label><input type="checkbox" name="is_compilation" value="1"'.($r['is_compilation']?' checked':'').'> Verzamelalbum</label><button class="secondary small" type="submit">Label opslaan</button></form>';$refreshControl=$r['barcode']?'<form method="post"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="form" value="refresh_record"><input type="hidden" name="id" value="'.$r['id'].'"><div class="actions"><button class="secondary" type="submit">Albumdata opnieuw ophalen</button></div></form>':'';layout($r['title'],'<section class="details"><div>'.$cover.'</div><div>'.$tags.'<h1>'.e($r['artist']).'<br>'.e($r['title']).'</h1><p class="muted">Jaar: '.e($year).' · Lengte: '.e(playtime($r['duration_seconds']?(int)$r['duration_seconds']:null)).'<br>Toegevoegd op: '.e($added).'</p>'.$compilationControl.$refreshControl.($r['barcode']?'<p class="muted">Barcode: '.e($r['barcode']).'</p>':'').'<h2>Tracklijst</h2>'.tracklistDisplay($r).'<form method="post"><input type="hidden" name="csrf" value="'.csrf().'"><input type="hidden" name="form" value="delete_record"><input type="hidden" name="id" value="'.$r['id'].'"><div class="actions"><button class="secondary" type="submit">Album verwijderen</button></div></form></div></section>'); }
$statement=db()->prepare('SELECT * FROM records WHERE user_id=? AND deleted_at IS NULL ORDER BY created_at DESC');$statement->execute([$_SESSION['user_id']]);$rows=$statement->fetchAll();$items='';foreach($rows as $r){$image=($r['cover_path']||$r['barcode'])?'<img class="cover" src="?action=image&amp;id='.$r['id'].'&amp;size=thumb" alt="">':'<div class="cover"></div>';$search=strtolower($r['artist'].' '.$r['title'].' '.$r['barcode']);$meta=($r['release_year']?:'—').' · '.playtime($r['duration_seconds']?(int)$r['duration_seconds']:null);$tagClass=$r['format']==='LP'?'tag tag-lp':'tag';$compilation=$r['is_compilation']?'<span class="tag tag-compilation">Verzamelalbum</span>':'';$items.='<article class="record" data-search="'.e($search).'" data-format="'.e($r['format']).'"><a href="?page=record&amp;id='.$r['id'].'">'.$image.'</a><div class="record-body"><div class="record-tags"><span class="'.$tagClass.'">'.e($r['format']).'</span>'.$compilation.'</div><div class="record-identity"><p><span>Artiest</span>'.e($r['artist']).'</p><p><span>Titel</span>'.e($r['title']).'</p></div><p>'.e((string)$meta).'</p></div></article>';}
layout('Collectie','<section class="hero"><h1>Je muziek, altijd bij de hand.</h1><p>Leg je cd’s en lp’s vast, inclusief hoes, tracklijst en barcode.</p><div class="actions"><a class="button" href="?page=add">+ Nieuwe uitgave</a><a class="button secondary" href="?page=scan">Barcode scannen</a><a class="button secondary" href="?page=scan&amp;mode=store">Scan in winkel</a></div></section><div class="toolbar"><strong id="collection-count">'.count($rows).' uitgave'.(count($rows)===1?'':'s').'</strong><div class="collection-filters"><select id="format-filter" aria-label="Filter op type"><option value="">Alle types</option><option value="CD">Alleen cd’s</option><option value="LP">Alleen lp’s</option></select><input id="filter" type="search" placeholder="Zoek artiest, titel of barcode" autocomplete="off"></div></div>'.($items?'<section class="collection collection-list">'.$items.'</section>':'<section class="card empty">Je collectie is nog leeg. <a href="?page=add">Voeg je eerste uitgave toe.</a></section>'));
